on:
  push:
    branches: [main]
  pull_request:

jobs:
  gitleaks:
    runs-on: docker
    container:
      # https://github.com/gitleaks/gitleaks#installing
      image: docker.io/zricethezav/gitleaks:latest
    steps:
      - name: Clone repository
        run: |
          git clone ${{ github.server_url }}/${{ github.repository }}.git .

      - name: Run gitleaks (push)
        if: github.event_name == 'push'
        run: |
          gitleaks detect --source . --verbose --exit-code 1

      - name: Run gitleaks (pull request)
        if: github.event_name == 'pull_request'
        run: |
          gitleaks detect --source . --verbose --exit-code 1 \
            --log-opts="${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
